### ISSUE TITLE
what's the meaning of [freq_ind = 42]？

### ISSUE THREAD

**Issue by 907711588** [YuriWayne42/hrtf_sht_personalization#1]
https://github.com/YuriWayne42/hrtf_sht_personalization/blob/99da8e025c858c4a8b99df9e9288ade5782c55ce/sht_preprocessing/HRTF_SHT_hutubsVersion.m#L34

Does this mean that only 42 points are taken in the frequency domain?

**Comment by YuriWayne42** [comment]
Hi, the freq_ind is just a demo frequency we chose to illustrate the HRTF magnitude directivity. The code "HRTF_SHT_MultiRun_hutubs" was then used to generate a matrix containing all the magnitude information for all subjects and all frequencies. Sorry for the confusion.
