### ISSUE TITLE
Please add an overview to the README.md

### ISSUE THREAD

**Issue by p-i-** [YuriWayne42/hrtf_sht_personalization#2]
Someone finding this repository from googling `HRTF github` will not get a clear idea of what this project accomplishes.

What goes in?
What comes out?
What is the basic mechanism?

Is it the case that one can adjust certain parameters, such as distance-between-ears, input a 3D location, and recover an impulse response?

Please prepend a preamble/overview to the README so that the reader has enough context with which to decide whether to dig deeper.

**Comment by yzyouzhang** [comment]
Thank you for your interest in our work! We updated the README.

The input is anthropometric measurements, and the output is the magnitude of the HRTF.
The basic mechanism is we use Spherical Harmonics Transform to extract the SH coefficients of the HRTF and then use a Deep Neural Network to predict the SH coefficients from the anthropometric measurements. 

To recover the Head Related Impulse Response is our ongoing work. Stay tuned!
